# Generated by Django 5.1.2 on 2024-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('struktur_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('child_id', models.IntegerField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'struktur',
            },
        ),
    ]
