# Generated by Django 5.1.2 on 2024-11-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structure',
            new_name='Struktur',
        ),
        migrations.AlterModelTable(
            name='struktur',
            table=None,
        ),
    ]
